=== EOX-A/ngeo-b/ngeo_browse_server/schemas/ngEOBrowseIngestionService.xsd
<xs:schema xmlns:bsi="http://ngeo.eo.esa.int/schema/browse/ingestion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:rep="http://ngeo.eo.esa.int/schema/browseReport" targetNamespace="http://ngeo.eo.esa.int/schema/browse/ingestion" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://ngeo.eo.esa.int/schema/browseReport" schemaLocation="IF-ngEO-BrowseReport-1.1.xsd"/>
	<xs:element name="ingestBrowse" type="rep:browseReportType"/>
	<xs:element name="ingestBrowseResponse" type="bsi:IngestBrowseResponseType"/>
	<xs:complexType name="BaseResponseType">
		<xs:sequence>
			<xs:element name="status" type="bsi:ResponseStatusType"/>
			<xs:element name="message" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="1024"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ingestionSummary" type="bsi:IngestionSummaryType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ResponseStatusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="success"/>
			<xs:enumeration value="partial"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="IngestionSummaryType">
		<xs:sequence>
			<xs:element name="toBeReplaced" type="xs:int"/>
			<xs:element name="actuallyInserted" type="xs:int"/>
			<xs:element name="actuallyReplaced" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RecordsResultType">
		<xs:sequence>
			<xs:element name="briefRecord" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="identifier">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:maxLength value="1024"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="status" type="bsi:IngestRecordStatusType"/>
						<xs:element name="error" type="bsi:ExceptionType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="IngestRecordStatusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="success"/>
			<xs:enumeration value="partial"/>
			<xs:enumeration value="failure"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="IngestBrowseResponseType">
		<xs:complexContent>
			<xs:extension base="bsi:BaseResponseType">
				<xs:sequence>
					<xs:element name="ingestionResult" type="bsi:RecordsResultType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!--######################################################################-->
	<!--Exceptions-->
	<!--######################################################################-->
	<xs:element name="ExceptionElement" type="bsi:ExceptionType"/>
	<xs:complexType name="ExceptionType">
		<xs:sequence>
			<xs:element name="exceptionCode">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="80"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="exceptionMessage">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="1024"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== EOX-A/ngeo-b/ngeo_browse_server/control/templates/control/ingest_response.xml
<?xml version="1.0" encoding="UTF-8"?>
<bsi:ingestBrowseResponse xsi:schemaLocation="http://ngeo.eo.esa.int/schema/browse/ingestion ../ngEOBrowseIngestionService.xsd"
xmlns:bsi="http://ngeo.eo.esa.int/schema/browse/ingestion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <bsi:status>{{ results.status }}</bsi:status>
    <bsi:ingestionSummary>
        <bsi:toBeReplaced>{{ results.to_be_replaced }}</bsi:toBeReplaced>
        <bsi:actuallyInserted>{{ results.actually_inserted }}</bsi:actuallyInserted>
        <bsi:actuallyReplaced>{{ results.actually_replaced }}</bsi:actuallyReplaced>
    </bsi:ingestionSummary>
    <bsi:ingestionResult>{% for result in results %}
        <bsi:briefRecord>
            <bsi:identifier>{{ result.identifier }}</bsi:identifier>
            <bsi:status>{{ result.status }}</bsi:status>{% if not result.success %}
            <bsi:error>
                <bsi:exceptionCode>{{ result.code }}</bsi:exceptionCode>
                <bsi:exceptionMessage>{{ result.message }}</bsi:exceptionMessage>
            </bsi:error>{% endif %}
        </bsi:briefRecord>{% endfor %}
    </bsi:ingestionResult>
</bsi:ingestBrowseResponse>

=== EOX-A/ngeo-b/ngeo_browse_server/ngeo_browse_server/control/templates/control/ingest_response.xml
<?xml version="1.0" encoding="UTF-8"?>
<bsi:ingestBrowseResponse xsi:schemaLocation="http://ngeo.eo.esa.int/schema/browse/ingestion ../ngEOBrowseIngestionService.xsd"
xmlns:bsi="http://ngeo.eo.esa.int/schema/browse/ingestion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <bsi:status>{{ result.status }}</bsi:status>
    <bsi:ingestionSummary>
        <bsi:toBeReplaced>{{ result.to_be_replaced }}</bsi:toBeReplaced>
        <bsi:actuallyInserted>{{ result.actually_inserted }}</bsi:actuallyInserted>
        <bsi:actuallyReplaced>{{ result.actually_replaced }}</bsi:actuallyReplaced>
    </bsi:ingestionSummary>
    <bsi:ingestionResult>{% for identifier, status, code, message in result %}
        <bsi:briefRecord>
            <bsi:identifier>{{ identifier }}</bsi:identifier>
            <bsi:status>{{ status }}</bsi:status>{% if code or message %}
            <bsi:error>
                <bsi:exceptionCode>{{ code }}</bsi:exceptionCode>
                <bsi:exceptionMessage>{{ message }}</bsi:exceptionMessage>
            </bsi:error>{% endif %}
        </bsi:briefRecord>{% endfor %}
    </bsi:ingestionResult>
</bsi:ingestBrowseResponse>

=== EOX-A/ngeo-b/schemas/examples/archive/ingestBrowseResponse_browseReport_regularGrid2.xml
<?xml version="1.0" encoding="UTF-8"?>
<bsi:ingestBrowseResponse xsi:schemaLocation="http://ngeo.eo.esa.int/schema/browse/ingestion ../ngEOBrowseIngestionService.xsd"
xmlns:bsi="http://ngeo.eo.esa.int/schema/browse/ingestion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <bsi:status>success</bsi:status>
    <bsi:ingestionSummary>
        <bsi:toBeReplaced>1</bsi:toBeReplaced>
        <bsi:actuallyInserted>1</bsi:actuallyInserted>
        <bsi:actuallyReplaced>0</bsi:actuallyReplaced>
    </bsi:ingestionSummary>
    <bsi:ingestionResult>
        <bsi:briefRecord>
            <bsi:identifier>ASAR</bsi:identifier>
            <bsi:status>success</bsi:status>
        </bsi:briefRecord>
    </bsi:ingestionResult>
</bsi:ingestBrowseResponse>
